services:
  cc-aligner:
    image: ghcr.io/glopix/cloreco-images/cc-aligner
    container_name: cc-aligner
    volumes:
      # mount config file of clone detection tool
      - ./CCAligner_config.cfg:/cloneDetection/Applications/CCAligner/config.cfg

      # mount config file of BigCloneEval commands (used by entrypoint.py)
      - ./entrypoint.cfg:/cloneDetection/entrypoint.cfg

      # directory: report from detectClones
      - ../reports/:/cloneDetection/reports/
      # directory: final report from evaluateTool
      - ../evaluation/:/cloneDetection/evaluation/

    #entrypoint: ["/bin/bash", "-c", "sleep 900000"]
