version: '3.10'
services:
  cc-aligner:
    image: git.uni-jena.de:5050/pi65gop/klondetektoren-automatisierung/cc-aligner
    container_name: cc-aligner
    volumes:
      # mount config file of clone detection tool
      - ./CCAligner_config.cfg:/cloneDetection/Applications/CCAligner/config.cfg

      # mount config file of BigCloneEval commands (used by entrypoint.py)
      - ./entrypoint.cfg:/cloneDetection/entrypoint.cfg

      # directory: report from detectClones 
      - ../reports/:/cloneDetection/reports/
      # directory: final report from evaluateTool 
      - ../evaluation/:/cloneDetection/evaluation/
    
    #entrypoint: /bin/bash -c "sleep 30000"
