services:
  nicad:
    depends_on:
      - benchmark
    image: ghcr.io/glopix/cloreco-images/nicad
    container_name: nicad
    volumes:
      # mount config file of clone detection tool
      - ./niCad_config.cfg:/cloneDetection/Applications/NiCad/config/myconfig.cfg

      # mount config file of BigCloneEval commands (used by entrypoint.py)
      - ./entrypoint.cfg:/cloneDetection/entrypoint.cfg

      # directory: report from detectClones
      - ../reports/:/cloneDetection/reports/
      # directory: final report from evaluateTool
      - ../evaluation/:/cloneDetection/evaluation/

      - share:/cloneDetection/benchmark

    entrypoint: ["/bin/bash", "-c", "sleep 900000"]

  benchmark:
    image: ghcr.io/glopix/cloreco-images/big-clone-eval-benchmark
    volumes:
      - share:/cloneDetection/BigCloneEval

volumes:
  share:
