services:
  redis:
    image: redis
    restart: unless-stopped

  web:
    image: ghcr.io/glopix/cloreco/cloreco-frontend
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
    # data directory
      - ./data/:/app/data/
    ports:
      - 5000:5000

  celery:
    image: ghcr.io/glopix/cloreco/cloreco-backend
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      # run pull for all images of clone detector tools and benchmarks at startup? (default: true)
      UPDATE_IMAGES_ON_STARTUP: True

      #SKIP_IMAGES_CHECK_ON_STARTUP: True

      # push new images ( created via 'add new Tool' web page) to the container image registry?
      PUSH_CREATED_IMAGES_TO_CONTAINER_REGISTRY: False
#    env_file:
#   #  container image registry credentials
#      - .env
    volumes:
    # data directory
      - ./data/:/app/data/
      #- ./app/project:/app/project/
      - /var/run/docker.sock:/var/run/docker.sock

    # give celery more time to abort the running task and remove the running containers at shutdown
    stop_grace_period: 30s


volumes:
  cloneDetection-data:
