version: '3.10'
services:
  bce:
    image: git.uni-jena.de:5050/pi65gop/klondetektoren-automatisierung/big-clone-eval-benchmark
    container_name: big-clone-eval-benchmark
    volumes:
      # mount config file of BigCloneEval commands (used by entrypoint.py)
      - ./entrypoint.cfg:/cloneDetection/entrypoint.cfg

      # directory: report from detectClones 
      - ../reports/:/cloneDetection/reports/
      # directory: final report from evaluateTool 
      - ../evaluation/:/cloneDetection/evaluation/

    entrypoint: /bin/bash -c "sleep 30000"