services:
  deckard:
    image: ghcr.io/glopix/cloreco-images/deckard
    container_name: deckard
    volumes:
      # mount config file
      - ./deckard_config.cfg:/cloneDetection/Applications/Deckard/config

      # mount config file of BigCloneEval commands (used by entrypoint.py)
      - ./entrypoint.cfg:/cloneDetection/entrypoint.cfg

      # directory: report from detectClones
      - ../reports/:/cloneDetection/reports/
      # directory: final report from evaluateTool
      - ../evaluation/:/cloneDetection/evaluation/

